spring:
  jpa:
    database: postgresql
    driver-class-name: org.postgresql.Driver
  datasource:
    url: ${DATA_STORE_DB_URL:jdbc:postgresql://localhost:5055/ccd_data?stringtype=unspecified}
    username: ${DATA_STORE_DB_USERNAME:ccd}
    password: ${DATA_STORE_DB_PASSWORD:ccd}
case_list_file: ${CASE_LIST_FILE}
dry_run: ${DRY_RUN:false}
